FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Mở cổng 8501 cho Streamlit
EXPOSE 8501

# Lệnh khởi chạy UI
CMD ["streamlit", "run", "src/api/streamlit_app.py", "--server.address=0.0.0.0"]