services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hieule
      MINIO_ROOT_PASSWORD: hieule123
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://api:8000/webhook/minio"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_volume:/data
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_volume:/qdrant/storage
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=hieule
      - MINIO_SECRET_KEY=hieule123
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - qdrant
      - minio
      - redis
    restart: always

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - .:/app  
    depends_on:
      - api
    restart: always

volumes:
  minio_data_volume:
  qdrant_data_volume: